# Generated by Django 5.2.4 on 2026-01-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_carbs_post_fat_post_kcal_post_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ocr_done',
            field=models.BooleanField(default=False),
        ),
    ]
